name: Create Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: get published files cache
        run: |
          git fetch origin processed_files:processed_files
          git checkout processed_files -- processed_files.json

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - id: get_changed_files
        name: Get changed files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"

      - name: Run script to create preview
        env:
          CHANGED_FILES: ${{ steps.get_changed_files.outputs.added_modified }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVIEW: True
        run: python -u lib/main.py

