name: Create Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - id: get_changed_files
        name: Get changed markdown files in posts
        uses: tj-actions/changed-files@v44
        with:
          files: posts/**.md

      - name: get published files cache
        if: steps.get_changed_files.outputs.any_changed == 'true'
        run: |
          git fetch origin processed_files:processed_files
          git checkout processed_files -- processed_files.json

      - name: Set up Python
        if: steps.get_changed_files.outputs.any_changed == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        if: steps.get_changed_files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run script to create preview
        if: steps.get_changed_files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.get_changed_files.outputs.all_changed_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVIEW: "True"
        run: python -u lib/main.py
