name: Publish Content

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: get published files cache
      run: |
        git fetch origin processed_files:processed_files
        git checkout processed_files -- processed_files.json

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run script to publish contents
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        MATRIX_ROOM_ID: ${{ secrets.MATRIX_ROOM_ID }}
        MATRIX_USER_ID: ${{ secrets.MATRIX_USER_ID }}
        SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      run: python main.py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: 'processed_files.json'
        branch: 'processed_files'