name: Publish Content

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install markdown atproto Mastodon.py beautifulsoup4

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: processed_files_dict
        path: processed_files.json

    - name: Run script to publish contents
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: python main.py
    
    - name: Upload dictionary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: processed_files_dict
        path: processed_files.json  
        
